"""add product dimensions

Revision ID: 2d0196135b64
Revises: 497e1366d447
Create Date: 2026-02-08 18:39:55.125291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0196135b64'
down_revision = '497e1366d447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('package_length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('package_width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('package_height', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('package_weight', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'package_weight')
    op.drop_column('products', 'package_height')
    op.drop_column('products', 'package_width')
    op.drop_column('products', 'package_length')
    # ### end Alembic commands ###
