"""Add sales_rep_id to clients

Revision ID: 497e1366d447
Revises: 3ffa533eed1f
Create Date: 2026-02-08 14:13:38.593104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497e1366d447'
down_revision = '3ffa533eed1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('sales_rep_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['sales_rep_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'sales_rep_id')
    # ### end Alembic commands ###
