"""add product components table

Revision ID: 9eed9ffec403
Revises: 953a38e36509
Create Date: 2026-02-08 19:41:23.485678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eed9ffec403'
down_revision = '953a38e36509'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=False),
    sa.Column('child_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_product_id', 'child_product_id', name='uq_product_component_parent_child')
    )
    op.create_index(op.f('ix_product_components_child_product_id'), 'product_components', ['child_product_id'], unique=False)
    op.create_index(op.f('ix_product_components_id'), 'product_components', ['id'], unique=False)
    op.create_index(op.f('ix_product_components_parent_product_id'), 'product_components', ['parent_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_components_parent_product_id'), table_name='product_components')
    op.drop_index(op.f('ix_product_components_id'), table_name='product_components')
    op.drop_index(op.f('ix_product_components_child_product_id'), table_name='product_components')
    op.drop_table('product_components')
    # ### end Alembic commands ###
